language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: H/BgNjeYdCPo5f44rOX0DB1VzdZCKzmKd3OMxUXHJedgZsJFW5WWfLP3M7tll9oPMjpG7U1CBOJ3LzObxcj8O6GH1ifpdE/Z1VuamgfDhJ+TKMA6sqrlrwoUj75QlrrEwQJktlUzff72YidCqtuUgWtTRJ3HgpmCHMXsnaaS7yp4AcsxuLqoVwsS4Ps6uaBJFfZhU/zG1GKUQFO3sJ6gav3Ie2iYxm57fKdjBO8pgb1wB0hlOV689I2S3IvFQFznjlxsQp/MF8LsttMoqqcA0HETWwT1TYWcikWABqzPks4KkNPkMlrHBK2T2mXowfjxr59i06+pVZjLWXvlGDiQD4OPpB2FTDV+bYNFR0oYmn0Wj1Ukv3hkqwcewiqnQhjU5uZH1NVOIllL9Vmi0nD5/EitWAyVcsVU/eKpff2ikKReIYEZfPSc4awPdx6O1ZCVQEU3mG2ugPNSAp+jlRWA2/tdJX9hnDzJcIPZO4i/fRP1dZGN0eRkLKM84/wHN4eQj2XnQyw0n5eUxftZYMibO3hHtbF6XLVlfo8lOT/AJlsSwzdIser2u3cu4/Z9Q0uyd3peuI2N90rP6G8IVbILIuWjpEuu+wh/bP3e+sRvOdkiGPcLF2Ea6fBjrYLAB9pBOwhzVYKs9OllaaYr3XL/CJgUkLcQCE4YrymraQFDucY=
